### ISSUE TITLE
多言語化

### ISSUE THREAD

**Issue by bishantakuma-abewadana** [belion-freee/hello-world-rails#10]
そいや忘れてた。

多言語化は案件進めてると結構カオスな感じになるので、なるべく階層化してわかりやすく作る。

多分、別ファイルに切り出すスタイルがいいんだと思うんだわ。

**Comment by belion-freee** [comment]
![shingo](https://user-images.githubusercontent.com/34331230/54495906-04d57f00-492c-11e9-8949-306333286831.jpg)
