### ISSUE TITLE
auto_load_paths使うな

### ISSUE THREAD

**Issue by bishantakuma-abewadana** [belion-freee/hello-world-rails#11]
Rails5からの仕様でproduction環境では `auto_load_path` で読み込まないという~クソ~仕様になったので、
`auto_load_paths`を`eager_load_paths`に変える。

<img src="http://d13n9ry8xcpemi.cloudfront.net/photo/odai/400/da3affe989ee7eacade6b64c34346498_400.jpg" with="30%">

[参考](https://qiita.com/joooee0000/items/3ab0f3d791e0d0beb639)

### 改修箇所
https://github.com/belion-freee/hello-world-rails/blob/master/config/application.rb

**Comment by belion-freee** [comment]
![shingo](https://user-images.githubusercontent.com/34331230/54495906-04d57f00-492c-11e9-8949-306333286831.jpg)
