### ISSUE TITLE
webpacker-dev-serverの同時起動

### ISSUE THREAD

**Issue by bishantakuma-abewadana** [belion-freee/hello-world-rails#46]
以下の要件を満たす

- webpacker-dev-serverの同時起動
- コンソールにログ出さないようにしたい

## 方針
foremanは使いたくない。同時起動するだけなら頑張ればシェルでできそう。
docker-compose.ymlはこのままでいいと思う。
qsスクリプトで対応するのが良さげ。
起動してるコンテナに `docker exec -d <コンテナ名>` すればいいので、コンテナ名取得できないか調べる。

**Comment by belion-freee** [comment]
> 同時起動するだけなら頑張ればシェルでできそう。
とか思ってたけど、そんなことなかったぜ！
スクリプトだと別タブ開くやり方しかできなかったので、サービスを別で作る。
サービス多すぎ問題。まあ、仕方ないか。。。

**Comment by belion-freee** [comment]
done
